### ISSUE TITLE
Lav diagrammer med system-overblik

### ISSUE THREAD

**Issue by xidus** [SDFIdk/AutoBernese#15]
Det centrale spørgsmål, denne opgave skal besvare, er: Hvordan flyder data fra aktører/datakilder til gennem vores GNSS-beregnings-arbejde til de modtagende aktører/systemer, der skal bruge dem?

Altså:

1. Hvem eller hvad leverer data/oplysninger/konfigurationer, som vi skal bruge i vores beregninger?
2. Hvilke processer tager/behandler/producerer hvilke data?
3. Hvem eller hvad er modtageren af hvilke data?

Formål:

* At have en beskrivelse af, hvad der skal laves, og hvorfor.
* At have en relativt detaljeret beskrivelse af de konkrete skridt, der af de enkelte brugere skal gennemgås i vores nuværende system-opsætninger for at kunne levere de resultater, der udgør hele eller dele af de slutprodukter, vi i kontoret står for at levere til os selv og vores eksterne modtagere.

Synsvinkel:

* Datas vej fra start til slut.

Slutprodukt:

* En grafisk repræsentation af datastrømmen, som giver os et overblik over, hvad der kan og bør automatiseres, når vi går i gang med implementeringsarbejdet.
* Slutproduktet skal mindst være på to niveauer jævnfør normal praksis/nomenklatur for data flow diagrammer: En system-konstekst, samt level 1-diagram, der viser AS-IS.
* Gerne et sæt diagrammer for hver type opgave:
  a. NKG
  b. Tjenesteberegninger
  c. KDI
  d. 5D

Antagelser:

1. Vores egne referencestationer får deres koordinat og relative hastighed til et givet tidspunkt/-rum i referencesystemet ETRS89 fra en beregning i NKG-regi, hvor vi sammenholder referencestationer i NKG.
2. Med referencestationernes koordinater holdt fast kan vi beregne koordinater til KDIs GNSS-modtagere, tjenesternes RTK-stationer, samt vores egne 5D-punkt-netværk.

**Comment by kbevers** [comment]
Vi vurderer at diagrammerne er tilstrækkelige færdige til at beskrive systemet som vi gerne ser det. Hvis der er behov for at justere gøres det løbende.
