### ISSUE TITLE
Bestil firewall-åbning til Oracle-serveren (se fire.ini-fil)

### ISSUE THREAD

**Issue by xidus** [SDFIdk/AutoBernese#19]
Der skal åbnes for adgang fra gnss til port 1521 på serveren ed databasen (se din `fire.ini`-fil for server-navn).

**Comment by xidus** [comment]
https://statensitprod.service-now.com/serviceportal/?id=ticket&table=sc_req_item&sys_id=15f1a8b31bf8ed5027b15605464bcbee&view=sp

**Comment by xidus** [comment]
Fik føjet de ønskede portåbninger til her til formiddag.
Nu kan man bruge FIRE på serveren:)

**Comment by kbevers** [comment]
Hurrra! Hvad manglede der? (jeg får ikke lov til at se sagen via linket ovenfor...)

**Comment by xidus** [comment]
Der manglede adgang til samme port på de fire andre IP-adresser, som programmet, åbenbart helt korrekt, forsøgte at forbinde til. Jeg skriver den samlede, nødvendige bestilling for serveren i dokumentationen, men ellers er oplysningerne i mappen med bestillingshistorik i serverens dokumentationsmappe på fællesdrevet.

**Comment by kbevers** [comment]
Super. Tak.
