### ISSUE TITLE
Afklaring af hvordan fælles datalager skal organiseres

### ISSUE THREAD

**Issue by xidus** [SDFIdk/AutoBernese#21]
Der skal tages stilling til hvilke data vi vil gemme lokalt, og hvilke der hentes når der er brug for dem.

Hvilke data er relevante?

- Satellitbaner?
- Ocean loading?
- RINEX data fra IGS stationer?
- ... ?

**Comment by kbevers** [comment]
Henrik opretter issues på de forskellige scripts der skal udvikles (punkterne sidst i txt-filen)

**Comment by kbevers** [comment]
Ovenstående forslag er baseret på strukturen i 5.2. Vi skal sikre at det også er kompatibelt med 5.4. Henrik forventer at blive klogere på det efter #33 er færdig (RNX2SNX-eksemplet).

**Comment by Aslak-Meister** [comment]
I forlængelse af vores diskussion vedr. opstilling af en fælles STA-fil, kan jeg bekræfte, at der findes et Bernese-program der kan merge to STA-filer - det hedder (selvfølgelig) STAMERGE. Udover at merge to filer kan programmet bl.a. sortere indholdet i en STA-fil, og nok så nyttigt kan det lave en ny STA-fil, der er et ekstrakt af en eksisterende STA-fil baseret på en fil med stationsnavne samt et angivet tidsvindue.

**Comment by xidus** [comment]
Afhænger af #59

**Comment by nho-sdfe** [comment]
Lidt mere afklaring... dog slet ikke færdig
f:\GRF\Faelles\Projekter\AutoBernese\arbejdsdokumenter\GEN_og_DATAPOOL_asmei_joamo_nho.txt

**Comment by xidus** [comment]
Som vi kom frem til i denne uge, så er denne opgave ikke helt færdig, da der forventeligt er filer, vi ikke helt véd, hvordan vi skal organisere.

Jeg fortsætter derfor arbejdet med at få downloadet de generelle filer og finder efterfølgende ud af, hvordan vi kan hente kampagne-specifikke RINEX-data fra eksterne kilder, hvor vi kun henter efter behov.

**Comment by xidus** [comment]
Lukker denne, da funktionaliteten er implementeret i juni 2023.
