### ISSUE TITLE
Opret Bernese-brugere på den nye server

### ISSUE THREAD

**Issue by xidus** [SDFIdk/AutoBernese#24]
Opret Bernese bruger-miljø til brugerne på den nye server (gnss), så vi kan afprøve og bekræfte Bernese-installationen pås serveren og teste/brugergodkende automatiseringsprogrammets funktionalitet.

**Bernese 5.4**

* [x] Joachim
* [x] Henrik
* [ ] Lars
* [x] Mette
* [ ] Aslak
* [ ] Kristian

**Comment by kbevers** [comment]
Vejledning til brugroprettelse flyttes ind i dokumentation af AutoBernese, herefter kan denne lukkes. Det er op til de enkelte brugere at sikre de er oprettet til Berneseberegning.
