### ISSUE TITLE
Lav prototype på brugergrænsefladen

### ISSUE THREAD

**Issue by xidus** [SDFIdk/AutoBernese#30]
Her kommer en liste med containere, der skal nedbrydes, specificeres og implementeres:

* [ ] Opret bruger-historier/brugsscenarier for det, der skal bygges. Der skal ikke bygges noget, der ikke skaber værdi.

* [x] CLI
  * [x] Opret prototype på brugergrænsefladen, der nemt kan ændres iterativt i samarbejdemed brugerne.
  * [x] Brugsscenarie(r)/-historie(r)
  * [x] Teknologi-afprøvning
  * [x] Specifikation/design, der imødekommer brugerhistorien.
  * [x] Implementering
* [ ] Datahenter (finde gerne selv bedre begreb for denne container)
  * [x] Brugsscenarie(r)/-historie(r)
  * [x] Teknologi-afprøvning
  * [x] Specifikation/design, der imødekommer brugerhistorien.
  * [ ] Implementering

Ovenstående er bare mine indfald. Lad os tale om dem og definere fremgangsmåder på kontoret:)

**Comment by kbevers** [comment]
Henrik forslår:


Tilføj en option `-w <ugenr>` eller `--gps-week <ugenr>` i forbindelse med eksemplet ovenfor `ab regn-kampagne`. Fidusen er at så kan programmte selv finde ud af hvilke stationer der er data fra. Vil i hvert fald være nyttigt ved 5D-beregninger, måske også andre.

Der kan sikkert også være fidus i et kunne give et andet tidsinterval, fx to gps-uger eller mellem to datoer. Et relevant eksempel her er GR96-kampagnen der løber over to ugers opmåling.

**Comment by xidus** [comment]
Som jeg ser denne nu, så må vi kunne udnytte:

1. Standard-funktionaliteten i Berneses PCF-scripts (kopiering af filer til kampagne)
2. Udnytte, at hver kampagnetype har en fast struktur. De eksisterende Perl-scripts gør allerede dét for NKG-kampagne, at den i start-kommandoen angivne GPS-uge bruges af programmet til at hente data tre uger tilbage. For 5D-punkter er der også en GPS-uge, som de tre opmplingsdage ligger i.

ad.2) Hvis man kan lave en skabelon til hver kampagnetype, der har en konfigurationsmulighed, der angiver intervaller, der skal hentes hvilke data ned for til DATAPOOL-området, så kan man slippe for at angive dette i oprettelsen.

**Comment by xidus** [comment]
Jeg lukker denne, da resten af opgaven har sin egen issue, som jeg aktivt arbejder på. Brugergrænsefladen tilapasses senere til nogle meningsfulde kommandoer.
