### ISSUE TITLE
Installer Bernese GNSS SOftware version 5.4 + afhængigheder

### ISSUE THREAD

**Issue by xidus** [SDFIdk/AutoBernese#32]
Bernese GNSS Software version 5.4 [BSW] har samme afhængigheder, som version 5.2. Disse er allerede installeret på serveren.

Når programmet er installeret skal man selv hente nogle tabeller (efemerider) fra NASAs JPL. Disse data skal samles og behandles af et værktøj, der omdanner data fra ASCII til binært format, så BSW nemmere kan bruge data internt.

Programmet, der gør dette er et fortran-program, der er oversat samtidig med de andre Fortran-programmer i byg-processen. Dét forklarer, hvorfor man selv skal kontrollere, at afvigelserne fra de medfølgende test-data ikke er af nogen betydning.

Man kontrollerer dette ved at se på output fra et andet Fortran-program, der sammenligner indholdet i den binære fil med test-data.

Er data gode nok, skal de kopieres over i $MODEL-mappen i BSW.

*   [x] Find placering til BSW 5.4
*   [x] Installér programmet, så det kan køres af en bruger.
*   [x] (Overvej og installér eventuelt flere instanser (miljøer) eller lav versionsstyrnig på kildefilerne.)
*   [x] Byg og installér JPL-data

**Comment by kbevers** [comment]
Bernese 5.4 er installeret. Bøvl med filrettigheder og test udestår. Se separate opgaver.
