### ISSUE TITLE
Kør Bernese 5.4-eksempelkampagne

### ISSUE THREAD

**Issue by xidus** [SDFIdk/AutoBernese#33]
Bernese kommer med en eksempelkampagne, der kan køres for at lære programmet bedre at kende, men også kontrollere, at installationen fungerer som den skal.

Sidstnævnte skal gøres, inden vi kan starte med at lave nye kampagner.

**Comment by nho-sdfe** [comment]
Har gennemført PPP-BPE example kampagnen uden problemer efter Joachim fik løst nogle skriverettigheder på serveren. Dog har jeg ligesom vores nordiske kollegaer konstateret af PPP-BPE bruger præcise baner, mens koordinaterne man skal sammenligne med, regnet af BERN, er regnet med rapid baner. Så hvis man skal sammenligne for alvor skal man regne PPP-BPE igen med rapid.
Først derefter kan vi se om vores Fortran compiler giver forskelle i koordinaterne i forhold til den compiler BERN har testet og regnet koordinaterne på.

**Comment by kbevers** [comment]
Fedt. Godt at vide at installationen er succesfuld!

> Så hvis man skal sammenligne for alvor skal man regne PPP-BPE igen med rapid.

Er der noget i vejen for at gøre det?

**Comment by nho-sdfe** [comment]
> Er der noget i vejen for at gøre det?
nej, det er sådan bare at gøre det...

**Comment by nho-sdfe** [comment]
Nå, det var ikke bare sådan at gøre det. Der mangler filer i eksemplet til at kunne køre en rapid løsning.
PPP-BPE'en forventer en rapid bias fil, afløseren for DBC filerne, og den findes ikke på BERN's ftp server før uge 2072 og eksemplet er fra 2044. Det er derfor ikke muligt at gentage helt præcist hvad BERN folkene har gjort. Jeg har sammenlignet en COD-bias fil med en COR-bias fil fra 2072 og de er ikke ens. Jeg tog alligevel en COD-bias fra 2044 og omdøbte den til en COR-bias. Så kører BPE'en. Men det offset i de endelige koordinater jeg så  mellem BERN og Præcis beregning er nøjagtig det samme (som ude på 5 decimal det samme) som mellem BERN og RAPID beregning. Der er et offset i XYZ på en halv til en hel mm i hver retning. Nu når det ikke er muligt at lave den præcis samme beregning som BERN har gjort, er det heller ikke muligt at vide om offsettet har noget med Fortran compileren at gøre.

Tænker at lave RNX2SNX eksemplet. Der er data nyere, så der burde vi være ude over bias fil problemet.

**Comment by nho-sdfe** [comment]
Har kørt RNX2SNX eksemplet. Og for at kunne sammenligne resultatet med BERN folkene var jeg ændre BPE'en til at regne med rapid baner. Hvis jeg bruger præcise baner regner den kun med GPS og GLONASS, mens rapid baner regner med GPS, GLONASS og GALILEO. Resultatet er at koordinaterne er ens, alle sammen helt ud på 5. decimal. Så det må vel være godkendt.

**Comment by xidus** [comment]
Lækkert. Jeg vil dele oplysningerom vores oversætter-software og version, så andre kan se, at det virker med denne opsætning.

Hvor lang tid vil det tage at gennemgå, hvad du har gjort for Lars, jeg og andre interesserede i gruppen? Kan vi tag den på mandag også?

**Comment by nho-sdfe** [comment]
Det vil ikke tage ret lang tid. Det er jo bare at vælge en dag med data i Configure->Set Session. 
Derefter BPE-> Start BPE processing. Vælg RNX2SNX.PCF i PANEL 2. Lave nogle fornuftige output fil navne i PANEL 3. Ændre Default value for V_ORBDIR og V_ORB fra COD til COR for rapid baner i PANEL 4.
Tryk RUN.

**Comment by xidus** [comment]
Tak, men det er ikke 'bare' :)

* Bruger du eksempelkampagnen?

Jeg kan selv prøve det af, men hvis du kan vise det på fem minutter, er det nemmere at gentage:)

**Comment by kbevers** [comment]
@nho-sdfe Vil du ikke finde et tidspunkt mandag eller tirsdag hvor du kan vise det til Joachim og Lars? Det er klart nemmest at du viser det.
