### ISSUE TITLE
BSW-API: Implementér opret-kampagne

### ISSUE THREAD

**Issue by xidus** [SDFIdk/AutoBernese#50]
Som bruger skal man kunne oprette en Bernese-kampagne af en bestemt type.

*   [x] Skriv modul, der opretter kampagne af en bestemt type. Hver type har en skabelon.
*   [x] Opret filmapper med minimal kampagne-opsætning (skal kunne køres) for hver kampagne-type.
*   [x] Design kampagne-administration: Skal kampagnenavnet altid med i kald eller skal det være muligt at sætte den aktive kampagne med programmet?

---

Overlap fra #53 (redigeret tekst nedenfor), som lukkes:

Vi antager,a t vi kan porette en ny kampagne i BSW 5.4 på samme måde som BSW 5.2, nemlig ved at kopiere en mappe, der fungerer som skabelon for en kampagne, over som en ny kampagne-mappe i CAMPAIGN54 og dérefter tilføje stien til kampagnemappen i kampagne-menu-filen i Bernese.

For hver kampagne-type, skal der være en skabelon, så man via `ab`-kommandoen kan oprette en kampagne baseret på en given skabelon.

De enkelte skabeloner er filer baseret på en default-fil, der kommer med pakken. Brugerne skal selv opbygge skabelonerne.

**Comment by kbevers** [comment]
Hvad betyder det her egentligt? Er det noget med Docker?

**Comment by xidus** [comment]
`gensta`:

* Der skal være adgang til ftp-serveren hos EUREF for at man kan hente STA-filen.
* [x] Jeg har bestilt adgang til tre FTP-servere, som er nævnt i den aktive autobpe.conf-fil, som bruges på MWs server.

**Comment by xidus** [comment]
*   Opret kampagne
    -   Givet:
        +   GPS-uge
    -   Opret en ny standard-kampagne, der kan vælges i Bernese GUI'en.
        +   Er kampagnen ikke en standard-kampagne, kan man altid lave en basis-kampagne i GUI'en og tilføje en kampagne-konfiguration.

**Comment by xidus** [comment]
Status på denne er, at der nu kan oprettes en mappe med kampagnen i en undermappe af Bernese-kampagne-mappen, og her kopieres en skabelon over, som brugeren selv skal lave. Som udgangspunkt kommer der en default skabelon med, når man opretter kampagner. Mappen med skabeloner skal vedligeholdes af brugerne og ligger ,hvor autobernese har sine 'runtime' filer så som log-filen og andet. default.skabelonen kommer med pakken og overføres, hvis ikek mappen med skabeloner findes i forvejen. Ellers forbliver mappen urørt.

Næste opgave er at få tilføjet de nødvendige filer fra Bernese-installationen til den oprettede kampagne, samt oprette filtrætet fra kampagne-mappens rod.

Når dette er gjort, kan man oprette en kampagne i Bernese med autobernese.

Næste issue handler om, hvordan man henter data til kampagnen, og dernæst igen skal BPE-processerne håndteres.

**Comment by xidus** [comment]
Man kan nu oprette en kampagne baseret på kampagne-navn (mappenavn i roden af standard-bernese kampagne-mappe), skabelon-fil, start- og slut-dato (begge inklusive i beregningen) for kampagnen.
